[package]
name = "lrpmp-macros"
version = "0.1.0"
authors = ["avitex <theavitex@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
lrpmp-spec = { version = "0.1", features = ["codegen"] }
syn = "~1"
quote = "~1"
proc-macro2 = "~1"
proc-macro-hack = "0.5"
once_cell = "1.3"
