[package]
name = "lrpmp"
version = "0.1.0"
authors = ["avitex <theavitex@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "~1", features = ["derive"] }
serde_json = "~1"
serde_cbor = "~0.11"
bytestring = "0.1"