[package]
name = "lrpmp-macros"
version = "0.1.0"
authors = ["avitex <theavitex@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
lrpmp-spec = { path = "../lrpmp-spec" }
syn = "~1"
quote = "~1"
proc-macro2 = "~1"
