[package]
name = "lrpmp"
version = "0.1.0"
authors = ["avitex <theavitex@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
bytestring = "0.1"
serde = { version = "~1", features = ["derive"] }
serde_json = "~1"
serde_cbor = "~0.11"
lrpmp-proc-macro = { path = "../lrpmp-proc-macro" }
